on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'V*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release Multi Platform

jobs:
  build-macos:
    name: Upload Release Asset macOS
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.6.8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list
      - name: Run fbs
        run: |
          fbs freeze
          fbs installer
          ls target
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/reporte_neurociencias.dmg #change to real name
          asset_name: reporte_neurociencias.dmg #change to real name
          tag: ${{ github.ref }}
          overwrite: true

  build-windows:
    name: Upload Release Asset Windows
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6.8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list
      - name: Run fbs and freeze application
        run: |
          fbs freeze
          fbs installer
          dir target
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/reporte_neurocienciasSetup.exe #change to real name {}Setup.exe
          asset_name: reporte_neurocienciasSetup.exe #change to real name {}Setup.exe
          tag: ${{ github.ref }}
          overwrite: true
